"""Initial migration

Revision ID: 1b5575208567
Revises:
Create Date: 2025-11-09 14:30:35.949531

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5575208567'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_ingestion_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrichment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('success_indicator', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ethogram_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_label')
    )
    op.create_table('observers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persistent_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cage_id', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('matriline', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('ingestion_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_session_id'], ['data_ingestion_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_cage_id'), 'animals', ['cage_id'], unique=False)
    op.create_index(op.f('ix_animals_persistent_id'), 'animals', ['persistent_id'], unique=True)
    op.create_table('behavior_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ontology_reference', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('ethogram_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ethogram_id'], ['ethogram_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('observation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('observer_name', sa.String(), nullable=True),
    sa.Column('observer_id', sa.Integer(), nullable=True),
    sa.Column('cage_id', sa.String(), nullable=True),
    sa.Column('matriline', sa.String(), nullable=True),
    sa.Column('reason_for_observation', sa.String(), nullable=True),
    sa.Column('observation_notes', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('fair_identifier', sa.String(), nullable=True),
    sa.Column('ethogram_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ethogram_version_id'], ['ethogram_versions.id'], ),
    sa.ForeignKeyConstraint(['observer_id'], ['observers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_sessions_started_at'), 'observation_sessions', ['started_at'], unique=False)
    op.create_table('behavior_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('modifiers', sa.JSON(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('sample_type', sa.String(), nullable=False),
    sa.Column('reason_for_observation', sa.String(), nullable=True),
    sa.Column('event_tags', sa.String(), nullable=True),
    sa.Column('observer_notes', sa.String(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('behavior_id', sa.Integer(), nullable=False),
    sa.Column('observer_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('batch_identifier', sa.String(), nullable=True),
    sa.Column('interaction_partner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['behavior_id'], ['behavior_definitions.id'], ),
    sa.ForeignKeyConstraint(['interaction_partner_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['observer_id'], ['observers.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['observation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_logs_timestamp'), 'behavior_logs', ['timestamp'], unique=False)
    op.create_table('enrichment_engagement_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('alert_triggered', sa.Boolean(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('cage_id', sa.String(), nullable=True),
    sa.Column('enrichment_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['enrichment_item_id'], ['enrichment_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrichment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('engagement_type', sa.String(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('enrichment_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['enrichment_item_id'], ['enrichment_items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['observation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hormone_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('hormone', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['observation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observation_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['observation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rank_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('elo_score', sa.Float(), nullable=False),
    sa.Column('davids_score', sa.Float(), nullable=True),
    sa.Column('instability_flag', sa.Boolean(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stress_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('stress_score', sa.Integer(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.Column('withdrawal', sa.Boolean(), nullable=False),
    sa.Column('fear_grimace', sa.Boolean(), nullable=False),
    sa.Column('self_biting', sa.Boolean(), nullable=False),
    sa.Column('pacing', sa.Boolean(), nullable=False),
    sa.Column('isolation', sa.Boolean(), nullable=False),
    sa.Column('cortisol_level', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['observation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_logs_date'), 'stress_logs', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stress_logs_date'), table_name='stress_logs')
    op.drop_table('stress_logs')
    op.drop_table('rank_scores')
    op.drop_table('observation_attachments')
    op.drop_table('incident_observations')
    op.drop_table('hormone_measurements')
    op.drop_table('enrichment_logs')
    op.drop_table('enrichment_engagement_summaries')
    op.drop_index(op.f('ix_behavior_logs_timestamp'), table_name='behavior_logs')
    op.drop_table('behavior_logs')
    op.drop_index(op.f('ix_observation_sessions_started_at'), table_name='observation_sessions')
    op.drop_table('observation_sessions')
    op.drop_table('behavior_definitions')
    op.drop_index(op.f('ix_animals_persistent_id'), table_name='animals')
    op.drop_index(op.f('ix_animals_cage_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_table('observers')
    op.drop_table('ethogram_versions')
    op.drop_table('enrichment_items')
    op.drop_table('data_ingestion_sessions')
    # ### end Alembic commands ###
