"""Add behavior modifiers

Revision ID: eb0872492d4e
Revises: 1b5575208567
Create Date: 2025-11-09 14:31:39.354791

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0872492d4e'
down_revision: Union[str, Sequence[str], None] = '1b5575208567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_modifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('behavior_definition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('modifier_type', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['behavior_definition_id'], ['behavior_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('behavior_modifiers')
    # ### end Alembic commands ###
